stages:
  - build
  - test
  - publish

include:
# DOCS: https://gitlab.internal.sanger.ac.uk/DERMATLAS/common/cicd-template/-/blob/develop/README.md
  - project: 'team113sanger/common/cicd-template'
    ref: 0.3.4
    file: '.gitlab-ci-components.yml'

#############
# TEMPLATES #
#############

.generic-wo-script-or-rules:
  extends:
    - .component-variables
    - .component-before_script
    - .component-after_script
    - .component-tags-shared-large-runner

.specific-variables:
  variables:
    USE_DOCKER_TARGET_STAGE: 0
    # We need to set this to 1 to enable BuildKit as the Dockerfile uses BuildKit features to speed up the build
    DOCKER_BUILDKIT: 1
    PRE_FETCH_BASE_IMAGE: gitlab-registry.internal.sanger.ac.uk/dermatlas/analysis-methods/maf:0.5.2

############
#   JOBS   #
############

build:
  stage: build
  extends:
    - .generic-wo-script-or-rules
    - .specific-variables
    - .component-script_docker-build
    - .component-rules-except-release
  timeout: 2 hours


publish-develop:
  stage: publish
  extends:
    - .generic-wo-script-or-rules
    - .specific-variables
    - .component-script-publish-develop-docker-image
    - .component-rules-develop-only


publish-tagged_and_latest_docker_images:
  stage: publish
  extends:
    - .generic-wo-script-or-rules
    - .specific-variables
    - .component-script-publish-tagged+latest-docker-image
    - .component-rules-tag-only
