services:
  maf:
    container_name: qc
    user: admin
    image: qc:local
    build:
      # ../ here means relative to the docker-compose.yml file.
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    # You want the container to stay up forever while you're developing.
    command: sleep infinity
    volumes:
      - type: bind
        # ../ here means relative to the docker-compose.yml file.
        source: ../
        target: /opt/repo/
    networks:
      - local-default

networks:
  local-default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1350
    ipam:
      config:
        - subnet: 192.168.4.0/24

